### ISSUE TITLE
Full Windows support

### ISSUE THREAD

**Issue by lpil** [lpil/filepath#1]

**Comment by NickSeagull** [comment]
Hi @lpil, I've tried to use this on Windows and I have seen some TODO comments on the code regarding missing support for Windows. I see there are some PRs related to Windows, would it be possible for me working on this part?

I actually started fixing `join` so that it works with Windows properly, but I soon realized that putting `is_windows` everywhere gets out of hand quickly, hindering readability.

I thought about splitting the code internally into two files, one for unix and one for windows, each having their own implementation. The current `filepath.gleam` file will be just a set of dispatchers.

**Comment by lpil** [comment]
What do you think is left to do? Reading the code now it looks like it is all implemented but the TODO comments are out of date.

**Comment by NickSeagull** [comment]
For example, `join` is not handling paths properly in Windows, as it is using `/` for the logic.

Another one is `is_absolute`, which checks if the string starts with `/`, but it should check for a drive letter rather. Same with `expand`.

In general, all the paths that are being handled with `/` instead of `\`

**Comment by lpil** [comment]
`/` is a valid separator on Windows, so that's fine.

If you'd like to make a PR for each missing feature that would be fab! All in one module please, using the pattern the code has established today.

**Comment by NickSeagull** [comment]
> / is a valid separator on Windows, so that's fine.

😲 I've been a Windows user for a long time and didn't know this lol

TIL thanks!
